version: '3'
services:
  node:
    container_name: node
    build: .
    volumes:
      - "./app:/src/app"
    ports:
      - 80:3000
    entrypoint: npm start
    environment:
      - slack_bot_token=${slack_bot_token}
      - slack_api_token=${slack_api_token}
      - localtunnel_subdomain=${localtunnel_subdomain}
